parameters:
#    cms_admin.example.class: Cms\AdminBundle\Example

services:
#    cms_admin.example:
#        class: %cms_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
